# Generated by Django 3.2.13 on 2022-07-26 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='label')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('url', models.CharField(blank=True, max_length=144, null=True, verbose_name='url')),
                ('button_text', models.CharField(blank=True, max_length=20, verbose_name='button text')),
                ('is_read', models.BooleanField(blank=True, default=False, verbose_name='is read')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notication',
                'verbose_name_plural': 'notications',
            },
        ),
    ]
