# Generated by Django 3.2.13 on 2022-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hours_worked',
            field=models.FloatField(blank=True, default=0.0, verbose_name='hours worked'),
        ),
    ]
