# Generated by Django 3.2.13 on 2022-07-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_solution_overall_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='tests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name='EvaluationTest',
        ),
    ]
