# Generated by Django 3.2.13 on 2022-07-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20220717_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='action',
            name='documentation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='documentation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='offer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='documentation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
