# Generated by Django 3.2.13 on 2022-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_implementation_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, verbose_name='is open'),
        ),
    ]
