# Generated by Django 3.2.13 on 2022-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_auto_20220718_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='offer',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='offer',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
