# Generated by Django 3.2.13 on 2022-07-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_auto_20220718_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootcause',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='documentation',
        ),
    ]
