# Generated by Django 3.2.13 on 2022-07-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_auto_20220714_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(blank=True, max_length=20, null=True)),
                ('display_type', models.JSONField(blank=True, default=list, null=True)),
                ('operating_system', models.JSONField(blank=True)),
                ('processor_type', models.CharField(blank=True, max_length=144, null=True)),
                ('number_of_processors', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('pci_slots', models.JSONField(blank=True, null=True)),
                ('hard_drives', models.JSONField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_descriptions', to='assets.device')),
            ],
            options={
                'verbose_name': 'system_description',
                'verbose_name_plural': 'system_descriptions',
            },
        ),
    ]
