# Generated by Django 3.2.13 on 2022-07-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='service_rates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
