# Generated by Django 3.2.13 on 2022-07-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('computer_type', models.CharField(blank=True, max_length=144)),
                ('peripherals', models.JSONField(blank=True, default=list, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.client')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
            },
        ),
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(blank=True, max_length=144, null=True, verbose_name='case')),
                ('motherboard', models.CharField(blank=True, max_length=144, null=True, verbose_name='motherboard')),
                ('bios', models.JSONField(blank=True, default=dict, null=True)),
                ('visual_display_unit', models.JSONField(blank=True, default=dict, null=True, verbose_name='visual display unit')),
                ('operating_system', models.CharField(blank=True, max_length=144, verbose_name='operating system')),
                ('architecture', models.CharField(blank=True, max_length=144, null=True)),
                ('processor', models.JSONField(blank=True, default=dict, null=True)),
                ('graphics_card', models.JSONField(blank=True, default=dict, null=True, verbose_name='graphics card')),
                ('sound_card', models.JSONField(blank=True, default=dict, null=True, verbose_name='sound card')),
                ('ram', models.JSONField(blank=True, default=dict, null=True)),
                ('pci_slots', models.JSONField(blank=True, default=list, null=True, verbose_name='pci slots')),
                ('hard_drives', models.JSONField(blank=True, default=list, null=True)),
                ('cooling', models.JSONField(blank=True, default=dict, null=True)),
                ('power_supply', models.JSONField(blank=True, default=dict, null=True, verbose_name='power supply')),
                ('documentation', models.JSONField(blank=True, default=list, null=True)),
                ('benchmarks', models.JSONField(blank=True, default=dict, null=True)),
                ('changes', models.JSONField(blank=True, default=list, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_snapshots', to='assets.device')),
            ],
            options={
                'verbose_name': 'system description',
                'verbose_name_plural': 'system descriptions',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=75, verbose_name='publisher')),
                ('name', models.CharField(blank=True, max_length=144, verbose_name='name')),
                ('version', models.CharField(blank=True, max_length=75, verbose_name='version')),
                ('description', models.TextField(blank=True, null=True)),
                ('documentation', models.JSONField(blank=True, default=list, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='assets.systemsnapshot')),
            ],
            options={
                'verbose_name': 'update',
                'verbose_name_plural': 'updates',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(blank=True, max_length=75, verbose_name='publisher')),
                ('name', models.CharField(blank=True, max_length=144, verbose_name='name')),
                ('version', models.CharField(blank=True, max_length=75, verbose_name='version')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='type')),
                ('license_key', models.CharField(blank=True, max_length=144, null=True, verbose_name='license key')),
                ('location', models.CharField(blank=True, max_length=144, verbose_name='location')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cost')),
                ('is_installed', models.BooleanField(blank=True)),
                ('documentation', models.JSONField(blank=True, default=list, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='assets.systemsnapshot')),
            ],
            options={
                'verbose_name': 'software',
                'verbose_name_plural': 'software',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cost')),
                ('documentation', models.JSONField(blank=True, default=list, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='assets.systemsnapshot')),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'parts',
            },
        ),
    ]
