# Generated by Django 3.2.13 on 2022-07-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.JSONField(blank=True, default=list, null=True)),
                ('operating_system', models.JSONField(blank=True, default=list)),
                ('processor_type', models.CharField(blank=True, max_length=144, null=True)),
                ('number_of_processors', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('pci_slots', models.JSONField(blank=True, default=list, null=True)),
                ('hard_drives', models.JSONField(blank=True, default=list, null=True)),
                ('documentation', models.JSONField(blank=True, default=list, null=True)),
                ('benchmarks', models.JSONField(blank=True, default=dict, null=True)),
                ('changes', models.JSONField(blank=True, default=list, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'system description',
                'verbose_name_plural': 'system descriptions',
            },
        ),
        migrations.RenameField(
            model_name='device',
            old_name='about',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='part',
            name='device',
        ),
        migrations.RemoveField(
            model_name='software',
            name='device',
        ),
        migrations.RemoveField(
            model_name='update',
            name='device',
        ),
        migrations.AddField(
            model_name='software',
            name='is_installed',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SystemDescription',
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_snapshots', to='assets.device'),
        ),
        migrations.AddField(
            model_name='part',
            name='snapshot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='assets.systemsnapshot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='snapshot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='software', to='assets.systemsnapshot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update',
            name='snapshot',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='assets.systemsnapshot'),
            preserve_default=False,
        ),
    ]
