# Generated by Django 3.2.13 on 2022-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='device',
            name='computer_type',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
